Name: product.rpc
ListenOn: 0.0.0.0:9001
Etcd:
  Hosts:
    - http://42.193.126.48:2379
  Key: product.rpc

Mysql:
  DataSource: root:123456@tcp(42.193.126.48:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: redis:6379
    Type: node